
# Don't need to call "all" from lib, because the makefile of exmaples will request it to produce recipies.
all:
	cd lib; make all; cd ..;
	cd examples; make all; cd ..;

remove:
	cd lib; make remove; cd ..;
	cd examples; make remove; cd ..;

